### PR TITLE
fixed composer.json autoload casing typo

### PR DESCRIPTION
**Pull request by rk3rn3r**
@druid628 there is a typo in the composer.json.
because you root namespace in ExactTargetBundle is with Uppercase "D" and on ExactTarget library lower case. For us composer autoloader won't work like this, so it would be great if you could merge this PR and create a new "stable" version tag 1.0.1 for this.

thanks in advance,
René

### CODE REVIEW

**Comment by druid628** [comment]
René
Thank you so much.  I've been unable to do much with this bundle the past few months. I realized this a few months ago and had it fixed in a localized repo but apparently I had not pushed those changes. Thanks for you contribution. I have more updates and changes in store for this bundle and hope to be able to finalize and push them up soon. 

I will merge the request, verify everything is working and create the new tag.

Thanks again.

.::. DruiD628 .::.

**Comment by druid628** [comment]
Completed. 
New stable is v1.1.0.

**Comment by rk3rn3r** [comment]
@druid628 thank you so much for the fast reaction! we already updated to your new version and everything seems running fine now.

**Comment by druid628** [comment]
Thank you for forcing me to update the library. Like  I said, I have some more changes/updates that I want to put in but have been unable find the time to finalize them for putting into the library. Hopefully this will give me the much needed shot in the arm to do that.

Thanks again for your submission!

**Pull request merged**
